---
- name: Set include path for stratum0
  set_fact:
    cvmfs_stratum0_include_path: "{{ role_path }}/variables"

- include_role: 
    name: cvmfs.roles/roles/cvmfs
  vars:
    cvmfs_role: stratum0
