---
- name: Set include path for clients
  set_fact:
    cvmfs_clients_include_path: "{{ role_path }}/variables"

- include_role: 
    name: "{{ role_path }}/../cvmfs"

- name: Make local settings file for the CVMFS domain, containing the node architecture
  ansible.builtin.copy:
    content: "{{ item.local_settings }}"
    #content: |
    #  ARCH={{ node_features.cpu.isa }}/{{ node_features.cpu.uarch }}
    dest: /etc/cvmfs/domain.d/{{ item.domain }}.local
    owner: root
    group: root
    mode: 0444
  with_items: "{{ rug_cvmfs_server_urls | rejectattr('local_settings', 'undefined') }}"

